ls
install.packages("fUnitRoots")
install.packages('forecast')
install.packages('forecast')
library('forecast')
getwd()
hp <- read.zoo("/home/wmy367/work/python/Financal_From_R/0933OS_Code/Chapter_1/UKHP.csv", sep=",", header=TRUE, format="%Y-%m", FUN=as.yearmon)
hp <- zoo::read.zoo("/home/wmy367/work/python/Financal_From_R/0933OS_Code/Chapter_1/UKHP.csv", sep=",", header=TRUE, format="%Y-%m", FUN=as.yearmon)
hp <- zoo::read.zoo("/home/wmy367/work/python/Financal_From_R/0933OS_Code/Chapter_1/UKHP.csv", sep=",", header=TRUE, format="%Y-%m", FUN=zoo::as.yearmon)
frequency(hp)
hp_ret <- diff(hp) / lag(hp, k = -1) *100
mod <- auto.arima(hp_ret, stationary = TRUE, seasonal = FALSE, ic='aic')
mod
confint(mod)
tsdiag(mod)
plot(mod$x,lty=1,main="UK",ylab="Return in percent", xlab="Date")
lines(fitted(mod), lty=2,lwd=2,col="red")
predict(mod, nh.head=3)
plot(forecast(mod))
install.packages('urca')
install.packages("urca")
library('urca')
print('op')
list()
list()
list.files(full.names = TRUE)
R.home()
library('here')
here::here()
library("zoo")
intc <- read.zoo("/home/wmy367/work/python/stocker/state/intro2R/intc.csv",header=TRUE, sep=",", format = "%Y-%m", FUN=as.yearmon)
intc
plot(intc, main="M returns ", xlab="Date", ylab="Return in percent")
Box.test(coredata(intc^2))
Box.test(coredata(intc^2),type="Ljung-Box", lag = 12)
library("FinTS")
install.packages("FinTS")
install.packages("FinTS")
library("FinTS")
ArchTest(coredata(intc))
help("coredata")
install.packages("rugarch")
install.packages("rugarch")
library("rugarch")
inct_garch11_spec <- ugarchspec(variance.model = list(garchOrder = c(1,1)), mean.model = list(armaOrder=c(0,0)))
inct_garch11_fit <- ugarchfit(spec=intc_garch11_spec, data=intc)
inct_garch11_fit <- ugarchfit(spec=inct_garch11_spec, data=intc)
inct_garch11_fit
savehistory("~/work/python/stocker/state/intro2R/R_cmd.R")
